### ISSUE TITLE
[Refactor] ResultDto 구조 변경

### ISSUE THREAD

**Issue by seongeon0620** [HSPU/PureSyncBack#48]
# 배경

- ResultDto 생성자를 각 서비스에 정의하고 사용하고 있어 이를 ResultDto 내부에 static 메서드로 재정의 예정

# 작업 상세 내용
- [x] ResultDto 생성자 메소드 추가

# 인수 조건

- 정상 작동 확인 후 병합

**Comment by HSPU** [comment]
확인했습니다
